/** @type {import('tailwindcss').Config} */
export default {
	content: ["./src/**/*.{js,ts,jsx,tsx,css,scss}"],
	theme: {
		extend: {},
		colors: {
			text: "var(--text-color)",
			background: "var(--background-color)",
			primary: {
				default: "var(--color-primary)",
				contrast: "var(--color-primary-contrast)",
				shade: "var(--color-primary-shade)",
				tint: "var(--color-primary-tint)",
			},
			secondary: {
				default: "var(--color-secondary)",
				contrast: "var(--color-secondary-contrast)",
				shade: "var(--color-secondary-shade)",
				tint: "var(--color-secondary-tint)",
			},
			tertiary: {
				default: "var(--color-tertiary)",
				contrast: "var(--color-tertiary-contrast)",
				shade: "var(--color-tertiary-shade)",
				tint: "var(--color-tertiary-tint)",
			},
			light: {
				default: "var(--color-light)",
				contrast: "var(--color-light-contrast)",
				shade: "var(--color-light-shade)",
				tint: "var(--color-light-tint)",
			},
			medium: {
				default: "var(--color-medium)",
				contrast: "var(--color-medium-contrast)",
				shade: "var(--color-medium-shade)",
				tint: "var(--color-medium-tint)",
			},
			dark: {
				default: "var(--color-dark)",
				contrast: "var(--color-dark-contrast)",
				shade: "var(--color-dark-shade)",
				tint: "var(--color-dark-tint)",
			},
			success: {
				default: "var(--color-success)",
				contrast: "var(--color-success-contrast)",
				shade: "var(--color-success-shade)",
				tint: "var(--color-success-tint)",
			},
			warning: {
				default: "var(--color-warning)",
				contrast: "var(--color-warning-contrast)",
				shade: "var(--color-warning-shade)",
				tint: "var(--color-warning-tint)",
			},
			danger: {
				default: "var(--color-danger)",
				contrast: "var(--color-danger-contrast)",
				shade: "var(--color-danger-shade)",
				tint: "var(--color-danger-tint)",
			},
			step: {
				"50": "var(--color-step-50)",
				"100": "var(--color-step-100)",
				"150": "var(--color-step-150)",
				"200": "var(--color-step-200)",
				"250": "var(--color-step-250)",
				"300": "var(--color-step-300)",
				"350": "var(--color-step-350)",
				"400": "var(--color-step-400)",
				"450": "var(--color-step-450)",
				"500": "var(--color-step-500)",
				"550": "var(--color-step-550)",
				"600": "var(--color-step-600)",
				"650": "var(--color-step-650)",
				"700": "var(--color-step-700)",
				"750": "var(--color-step-750)",
				"800": "var(--color-step-800)",
				"850": "var(--color-step-850)",
				"900": "var(--color-step-900)",
				"950": "var(--color-step-950)",
			},
		},
	},
	plugins: [],
};
