/** @type {import('tailwindcss').Config} */
export default {
	content: ["./src/**/*.{js,ts,jsx,tsx,css,scss}"],
	theme: {
		extend: {
			boxShadow: {
				"up-2xl": "0 -25px 50px -12px rgba(0, 0, 0, 0.25)",
			},
		},
		colors: {
			text: {
				default: "var(--text-color)",

				step: {
					"50": "var(--text-color-step-50)",
					"100": "var(--text-color-step-100)",
					"150": "var(--text-color-step-150)",
					"200": "var(--text-color-step-200)",
					"250": "var(--text-color-step-250)",
					"300": "var(--text-color-step-300)",
					"350": "var(--text-color-step-350)",
					"400": "var(--text-color-step-400)",
					"450": "var(--text-color-step-450)",
					"500": "var(--text-color-step-500)",
					"550": "var(--text-color-step-550)",
					"600": "var(--text-color-step-600)",
					"650": "var(--text-color-step-650)",
					"700": "var(--text-color-step-700)",
					"750": "var(--text-color-step-750)",
					"800": "var(--text-color-step-800)",
					"850": "var(--text-color-step-850)",
					"900": "var(--text-color-step-900)",
					"950": "var(--text-color-step-950)",
				},
			},
			border: {
				default: "var(--background-color-step-300, #b3b3b3)",
			},
			background: {
				default: "var(--background-color)",
				shade: "var(--toolbar-background, var(--background-color, #fff))",
				tint: "rgba(var(--text-color-rgb, 0, 0, 0), 0.12)",

				step: {
					"50": "var(--background-color-step-50)",
					"100": "var(--background-color-step-100)",
					"200": "var(--background-color-step-200)",
					"150": "var(--background-color-step-150)",
					"250": "var(--background-color-step-250)",
					"300": "var(--background-color-step-300)",
					"350": "var(--background-color-step-350)",
					"400": "var(--background-color-step-400)",
					"450": "var(--background-color-step-450)",
					"500": "var(--background-color-step-500)",
					"550": "var(--background-color-step-550)",
					"600": "var(--background-color-step-600)",
					"650": "var(--background-color-step-650)",
					"700": "var(--background-color-step-700)",
					"750": "var(--background-color-step-750)",
					"800": "var(--background-color-step-800)",
					"850": "var(--background-color-step-850)",
					"900": "var(--background-color-step-900)",
					"950": "var(--background-color-step-950)",
				},
			},
			primary: {
				default: "var(--color-primary)",
				contrast: "var(--color-primary-contrast)",
				shade: "var(--color-primary-shade)",
				tint: "var(--color-primary-tint)",
			},
			secondary: {
				default: "var(--color-secondary)",
				contrast: "var(--color-secondary-contrast)",
				shade: "var(--color-secondary-shade)",
				tint: "var(--color-secondary-tint)",
			},
			tertiary: {
				default: "var(--color-tertiary)",
				contrast: "var(--color-tertiary-contrast)",
				shade: "var(--color-tertiary-shade)",
				tint: "var(--color-tertiary-tint)",
			},
			light: {
				default: "var(--color-light)",
				contrast: "var(--color-light-contrast)",
				shade: "var(--color-light-shade)",
				tint: "var(--color-light-tint)",
			},
			medium: {
				default: "var(--color-medium)",
				contrast: "var(--color-medium-contrast)",
				shade: "var(--color-medium-shade)",
				tint: "var(--color-medium-tint)",
			},
			dark: {
				default: "var(--color-dark)",
				contrast: "var(--color-dark-contrast)",
				shade: "var(--color-dark-shade)",
				tint: "var(--color-dark-tint)",
			},
			success: {
				default: "var(--color-success)",
				contrast: "var(--color-success-contrast)",
				shade: "var(--color-success-shade)",
				tint: "var(--color-success-tint)",
			},
			warning: {
				default: "var(--color-warning)",
				contrast: "var(--color-warning-contrast)",
				shade: "var(--color-warning-shade)",
				tint: "var(--color-warning-tint)",
			},
			danger: {
				default: "var(--color-danger)",
				contrast: "var(--color-danger-contrast)",
				shade: "var(--color-danger-shade)",
				tint: "var(--color-danger-tint)",
			},
			active: {
				text: "var(--active-text-color)",
				background: "var(--active-background-color)",
			},
			transparent: "transparent",
		},
	},
	plugins: [],
};
